import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  index,
  integer,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { users } from "./auth-schema";
import { timestamps } from "./columns";

/**
 * The client registry (openspec change add-client-registry). Conventions from
 * AGENTS.md: uuid keys generated in Postgres, timestamptz, money in minor
 * units, every foreign key indexed. Database constraints repeat the Zod rules
 * for ranges and required pairs, so no path (including a future job) can store
 * invalid data.
 */

export const clientStatus = pgEnum("client_status", [
  "onboarding",
  "active",
  "paused",
  "offboarded",
]);
export const analyticsOwnership = pgEnum("analytics_ownership", ["open_waters", "client_owned"]);
export const siteFramework = pgEnum("site_framework", ["astro", "next", "other"]);
export const posthogRegion = pgEnum("posthog_region", ["eu", "us"]);
export const connectionStatus = pgEnum("connection_status", [
  "ok",
  "unauthorised",
  "project_not_found",
  "error",
]);
export const currency = pgEnum("currency", ["GBP", "EUR", "USD"]);
export const figureSource = pgEnum("figure_source", ["client_confirmed", "open_waters_estimate"]);
/** The contract package's measurement tiers (add-provisioning, design D5a). */
export const measurementTier = pgEnum("measurement_tier", ["essentials", "insights", "growth"]);
/** A search property's last check (add-search-console, design D7). */
export const searchCheckStatus = pgEnum("search_check_status", [
  "readable",
  "no_access",
  "check_failed",
]);
export const siteChangeKind = pgEnum("site_change_kind", [
  "launch",
  "design",
  "content",
  "campaign",
  "experiment",
  "tracking",
]);

export const clients = pgTable(
  "clients",
  {
    id: uuid().primaryKey().defaultRandom(),
    slug: text().notNull().unique(),
    name: text().notNull(),
    status: clientStatus().notNull().default("onboarding"),
    analyticsOwnership: analyticsOwnership().notNull(),
    regulated: boolean().notNull().default(false),
    ...timestamps,
  },
  table => [index("clients_status_idx").on(table.status)],
);

export const sites = pgTable(
  "sites",
  {
    id: uuid().primaryKey().defaultRandom(),
    // No cascade: clients are never deleted (spec: offboard instead).
    clientId: uuid()
      .notNull()
      .references(() => clients.id),
    productionUrl: text().notNull().unique(),
    framework: siteFramework().notNull(),
    repository: text(),
    launchedOn: date({ mode: "string" }),
    taxonomyVersion: integer().notNull(),
    timezone: text().notNull(),
    // Whether the site runs a consent banner. Only such a site is expected to
    // send consent_updated; see the expected-event defaults. Written from the
    // measurement tier since add-provisioning, never set on its own.
    hasConsentBanner: boolean().notNull().default(false),
    // Aggregate heatmaps, a per-client decision allowed at every tier.
    usesHeatmaps: boolean().notNull().default(false),
    measurementTier: measurementTier().notNull().default("essentials"),
    // The guard on the higher tiers: which tier a partner last confirmed the
    // banner and privacy page for. Cleared whenever the tier changes.
    tierConfirmedFor: measurementTier(),
    tierConfirmedAt: timestamp({ withTimezone: true }),
    tierConfirmedBy: uuid().references(() => users.id, { onDelete: "set null" }),
    // A site that took over an older site's domain: its first search pull
    // backfills, and reports label the older data "Previous site".
    replacesExistingSite: boolean().notNull().default(false),
    // Words that mark a search query as branded, lowercased. Applied when read.
    brandTerms: text()
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    ...timestamps,
  },
  table => [
    index("sites_client_id_idx").on(table.clientId),
    index("sites_tier_confirmed_by_idx").on(table.tierConfirmedBy),
    check(
      "sites_tier_confirmation_complete",
      sql`(${table.tierConfirmedFor} is null) = (${table.tierConfirmedAt} is null)`,
    ),
  ],
);

export const reportRecipients = pgTable(
  "report_recipients",
  {
    id: uuid().primaryKey().defaultRandom(),
    clientId: uuid()
      .notNull()
      .references(() => clients.id),
    name: text().notNull(),
    // Stored lower-cased, so the unique constraint is case-insensitive.
    email: text().notNull(),
    ...timestamps,
  },
  table => [
    unique("report_recipients_client_email_unique").on(table.clientId, table.email),
    index("report_recipients_client_id_idx").on(table.clientId),
  ],
);

export const posthogConnections = pgTable("posthog_connections", {
  // Generated by the application before insert: the id is the associated data
  // the API key is encrypted against, so it must be known before the row exists.
  id: uuid().primaryKey(),
  siteId: uuid()
    .notNull()
    .unique()
    .references(() => sites.id, { onDelete: "cascade" }),
  region: posthogRegion().notNull(),
  projectId: integer().notNull(),
  apiKeyCiphertext: text().notNull(),
  keyVersion: integer().notNull(),
  keyLast4: text().notNull(),
  lastCheckAt: timestamp({ withTimezone: true }),
  lastCheckStatus: connectionStatus(),
  lastCheckMessage: text(),
  ...timestamps,
});

export const searchConsoleProperties = pgTable("search_console_properties", {
  id: uuid().primaryKey().defaultRandom(),
  siteId: uuid()
    .notNull()
    .unique()
    .references(() => sites.id, { onDelete: "cascade" }),
  property: text().notNull(),
  lastCheckAt: timestamp({ withTimezone: true }),
  lastCheckStatus: searchCheckStatus(),
  lastCheckMessage: text(),
  /** When a replacement site's history was backfilled from this engine. */
  backfilledAt: timestamp({ withTimezone: true }),
  ...timestamps,
});

/** The site as Bing Webmaster Tools lists it, and its last check. */
export const bingWebmasterSites = pgTable("bing_webmaster_sites", {
  id: uuid().primaryKey().defaultRandom(),
  siteId: uuid()
    .notNull()
    .unique()
    .references(() => sites.id, { onDelete: "cascade" }),
  siteUrl: text().notNull(),
  lastCheckAt: timestamp({ withTimezone: true }),
  lastCheckStatus: searchCheckStatus(),
  lastCheckMessage: text(),
  /** When a replacement site's history was backfilled from this engine. */
  backfilledAt: timestamp({ withTimezone: true }),
  ...timestamps,
});

export const siteExpectedEvents = pgTable(
  "site_expected_events",
  {
    id: uuid().primaryKey().defaultRandom(),
    siteId: uuid()
      .notNull()
      .references(() => sites.id, { onDelete: "cascade" }),
    event: text().notNull(),
    ...timestamps,
  },
  table => [unique("site_expected_events_site_event_unique").on(table.siteId, table.event)],
);

export const siteCommercialContext = pgTable(
  "site_commercial_context",
  {
    id: uuid().primaryKey().defaultRandom(),
    siteId: uuid()
      .notNull()
      .unique()
      .references(() => sites.id, { onDelete: "cascade" }),
    leadValueMinor: integer(),
    currency: currency(),
    leadToCustomerRate: numeric({ precision: 5, scale: 4 }),
    source: figureSource(),
    ...timestamps,
  },
  table => [
    check(
      "site_commercial_context_source_required",
      sql`(${table.leadValueMinor} is null and ${table.leadToCustomerRate} is null) or ${table.source} is not null`,
    ),
    check(
      "site_commercial_context_currency_required",
      sql`${table.leadValueMinor} is null or ${table.currency} is not null`,
    ),
    check(
      "site_commercial_context_rate_range",
      sql`${table.leadToCustomerRate} is null or (${table.leadToCustomerRate} >= 0 and ${table.leadToCustomerRate} <= 1)`,
    ),
    check(
      "site_commercial_context_value_non_negative",
      sql`${table.leadValueMinor} is null or ${table.leadValueMinor} >= 0`,
    ),
  ],
);

export const siteChanges = pgTable(
  "site_changes",
  {
    id: uuid().primaryKey().defaultRandom(),
    siteId: uuid()
      .notNull()
      .references(() => sites.id, { onDelete: "cascade" }),
    occurredOn: date({ mode: "string" }).notNull(),
    kind: siteChangeKind().notNull(),
    title: varchar({ length: 120 }).notNull(),
    detail: text(),
    expectedEffect: text(),
    ...timestamps,
  },
  table => [index("site_changes_site_occurred_idx").on(table.siteId, table.occurredOn.desc())],
);
