/**
 * Drizzle schema. App tables arrive with the OpenSpec change that needs them.
 *
 * Better Auth's tables live in auth-schema.ts, generated by `pnpm auth:schema`
 * and not edited by hand: regenerate it after changing the auth configuration,
 * then run `pnpm db:generate`. They use Better Auth's column types (timestamp
 * without time zone), an accepted exception to the timestamptz convention.
 */
export * from "./auth-schema";
