/**
 * Drizzle schema.
 *
 * Better Auth's tables live in auth-schema.ts, generated by `pnpm auth:schema`
 * and not edited by hand: regenerate it after changing the auth configuration,
 * then run `pnpm db:generate`. They use Better Auth's column types (timestamp
 * without time zone), an accepted exception to the timestamptz convention.
 *
 * The client registry lives in registry-schema.ts, and the nightly snapshot's
 * tables in snapshot-schema.ts.
 */
export * from "./auth-schema";
export * from "./registry-schema";
export * from "./snapshot-schema";
